FROM node:12-alpine

# we might accidentally overwrite existing folders of the base image.
# this is a container directory
WORKDIR /abb


#Copy the dependencies file
# COPY ./package.json ./
# COPY ./packages/server/package.json ./packages/server/
# COPY ./packages/common/package.json ./packages/common/

# # RUN npm i -g yarn 999   # node 13 버전은 yarn 사전 탑재됨
# RUN yarn install

COPY ./ ./
COPY ./.env.local ./.env
ARG NODE_ENV
RUN yarn install --${NODE_ENV}

# .env 파일은 copy 안됨
COPY ./packages/server/.env.development ./packages/server/.env

# RUN ls -a
# RUN ls -a ./packages/server/



# TypeORM 설정 관련 
# COPY ./ormconfig.json ./


ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

# 컨테이너 위치 변경
# WORKDIR /app/packages/server/


