version: "3"
services:

    frontend:
        container_name: frontend
        build: 
            context: ../
            dockerfile: ./dockerCompose/Dockerfile.web.local.compose
        image: kcod/abbfront:latest
        ports:
            - "80:3000"
        networks:
            - net-abb
        environment:
            - CHOKIDAR_USEPOLLING=true  # hot-reloading will work
            - REACT_APP_SERVER_URL=${REACT_APP_SERVER_URL}:${SERVER_PORT}
        volumes:
            - ../:/abb/
        command:   
            - /bin/sh
            - -c 
            - "yarn start"

volumes:
    rdb-data:
networks:
    net-abb: